FCUD/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from .views import  ThanksTemplateView ,AccountCreateView ,AccountDetailView,AccountUpdateView,AccountDeleteView,AccountlistView

urlpatterns = [

    path('',AccountlistView.as_view(),name="list"),
    path('create/',AccountCreateView.as_view(),name="Create"),
    path('update/<int:pk>', AccountUpdateView.as_view(), name="Update"),
    path('detail/<int:pk>',AccountDetailView.as_view(),name="Details"),
    path('delete/<int:pk>',AccountDeleteView.as_view(),name="Delete"),
    path('thankyou/',ThanksTemplateView.as_view(),name="thanks"),


]

myapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Account(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    password =models.CharField(max_length=20)

    # def get_absolute_url(self):
    #     return reverse("details" , kwargs={"pk": self.pk})

myapp/forms.py
from django import forms



class ContactForm(forms.Form):
    name = forms.CharField(max_length=20)
    email = forms.EmailField()
    msg = forms.CharField(widget=forms.Textarea)

myapp/views.py
from django.shortcuts import render ,HttpResponseRedirect
from .forms import ContactForm
from .models import Account

from django.views.generic.edit import  CreateView,UpdateView,DeleteView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import  ListView

# Create your views here.
#
# class ContactFormView(FormView):
#     template_name = "home.html"
#     form_class = ContactForm
#     success_url = '/thankyou/'
#
#
#     def form_valid(self, form):
#         print(form.cleaned_data['name'])
#         print(form.cleaned_data['email'])
#         print(form.cleaned_data['msg'])
#         return super().form_valid(form)
#         # return HttpResponseRedirect('/thankyou/')


# List View (Home Page )

class AccountlistView(ListView):
    model = Account
    template_name = "list.html"


# CreateView

class AccountCreateView(CreateView):
    template_name = "account.html"
    model = Account
    fields = '__all__'
    success_url = '/'


    def get_form(self):
        form =super().get_form()
        form.fields['name'].widget = forms.TextInput(attrs={'class':'myclass'})
        form.fields['email'].widget = forms.EmailInput(attrs={'class' : 'myclass'})
        form.fields['password'].widget = forms.PasswordInput(attrs={'class' :'myclass'})
        return form

# Detail View

class AccountDetailView(DetailView):
    template_name = "details.html"
    model = Account


# Update View

class AccountUpdateView(UpdateView):
    template_name = "account.html"
    model = Account
    fields = '__all__'
    success_url = '/'

    def get_form(self) :
        form = super().get_form()
        form.fields['name'].widget = forms.TextInput(attrs={'class' : 'myclass'})
        form.fields['email'].widget = forms.EmailInput(attrs={'class' : 'myclass'})
        form.fields['password'].widget = forms.PasswordInput(attrs={'class' : 'myclass'})
        return form

# Delete View

class AccountDeleteView(DeleteView):
    template_name = 'delete.html'
    model = Account
    success_url = '/'


# Thanks Message For  Template View

class ThanksTemplateView(TemplateView):
    template_name = "thanks.html"

myapp/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
   <input type="submit" value="Submit">

</form>
</body>
</html>

myapp/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>delete</title>
</head>
<body>
<h1>Are you  sure for delete ?</h1>
<form method="post">
    {%csrf_token%}
    <input type="submit" value="Delete"><br><hr>
    <a href="{% url 'Create'%}">Cancel</a>


</form>
</body>
</html>

myapp/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>
 id: {{account.id}}<hr>
 name : {{account.name}}<hr>
email : {{account.email}}<hr>
password :{{account.password}}</h1>
</body>
</html>

myapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
   <input type="submit" value="Submit">

</form>
</body>
</html>

myapp/templates/list.html
<html>
<body>
<style>
  *{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
    background: rgba( 71, 147, 227, 1);
}
h1{
    text-align: center;
    background: white;
    font-size: 35px;
    text-transform: uppercase;
    letter-spacing: 5px;
    color: green;
    padding: 30px;
}
h2{
background: white;
    text-align: justify;
    font-size: 28px;
    text-transform: uppercase;
    letter-spacing: 5px;
    color: black;
    padding: 50px;
}

/* Table Styles */

.table-wrapper{
    margin: 15px 100px 100px;

}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: #4FC3A1;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: #324960;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}

/* Responsive */

@media (max-width: 767px) {

    .fl-table {
        display: block;
        width: 100%;
    }
    .table-wrapper:before{
        content: "Scroll horizontally >";
        display: block;
        text-align: right;
        font-size: 11px;
        color: white;
        padding: 0 0 10px;
    }
    .fl-table thead, .fl-table tbody, .fl-table thead th {
        display: block;
    }
    .fl-table thead th:last-child{
        border-bottom: none;
    }
    .fl-table thead {
        float: left;
    }
    .fl-table tbody {
        width: auto;
        position: relative;
        overflow-x: auto;
    }
    .fl-table td, .fl-table th {
        padding: 20px .625em .625em .625em;
        height: 60px;
        vertical-align: middle;
        box-sizing: border-box;
        overflow-x: hidden;
        overflow-y: auto;
        width: 110px;
        font-size: 13px;
        text-overflow: ellipsis;
    }
    .fl-table thead th {
        text-align: left;
        border-bottom: 1px solid #f7f7f9;
    }
    .fl-table tbody tr {
        display: table-cell;
    }
    .fl-table tbody tr:nth-child(odd) {
        background: none;
    }
    .fl-table tr:nth-child(even) {
        background: transparent;
    }
    .fl-table tr td:nth-child(odd) {
        background: #F8F8F8;
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tr td:nth-child(even) {
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tbody td {
        display: block;
        text-align: center;
    }
.button {
border: none;
color: white;
padding: 15px 32px;
text-align: center;
text-decoration: none;
display: inline-block;
font-size: 16px;
margin: 4px 2px;
cursor: pointer;
}
}
</style>


<h1>CRUD APP USING CLASS BASE VIEW</h1>
<!--<h2>Account Table Details</h2>-->
<div class="container-fluid">
<div class="table-wrapper">
   <button><a href="{% url 'Create' %}">ADD ACCOUNT</a></button>
    <br><br>
    <table class="fl-table">

        <thead>
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>EMAIL</th>
            <th>PASSWORD</th>
            <th>UPDATE</th>
            <th>DELETE</th>
        </tr>
        </thead>
        <tbody>
     {% for i in account_list %}
          <tr>
            <td>{{i.id}}</td>
            <td>{{i.name}}</td>
            <td>{{i.email}}</td>
            <td>{{i.password}}</td>
            <td><a href="{% url 'Update' i.pk %}">Edit</a></td>
            <td><a href="{% url 'Delete' i.pk %}">Delete</a></td>
          </tr>
    {% endfor %}

        <tbody>
    </table>
</div>
    </div>
</body>
</html>

myapp/templates/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Congratulations..</h1>
<h2>Your data has been update successfully...</h2>
</body>
</html>